# Lab 9: Support Vector Machines

The objective of this lab is

In [1]:
import warnings
warnings.filterwarnings('ignore')

from time import time
from datetime import timedelta

import pandas as pd
import seaborn as sns
import numpy as np

from dython.nominal import associations
from dython.nominal import correlation_ratio
from dython.nominal import cramers_v

from scipy.stats import chi2_contingency 
from scipy.stats import pearsonr 

from sklearn.metrics import f1_score, accuracy_score
from sklearn.preprocessing import minmax_scale

from sklearn.svm import LinearSVR, SVR, SVC
from sklearn.neighbors import KNeighborsRegressor

from sklearn.datasets import fetch_lfw_people
from sklearn.model_selection import train_test_split

from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report

from matplotlib import pyplot as plt

In [9]:
data_learn = pd.read_csv("log_ILDS_train_X.csv", sep = ",", decimal = ".")
X_learn = data_learn.drop(columns = ["Target"])
y_learn = data_learn["Target"]
X_test = pd.read_csv("log_ILDS_test_X.csv", sep = ",", decimal = ".")

X_learn["Female"] = X_learn["Female"].astype("object")
y_learn = y_learn.astype("object")
X_test["Female"] = X_test["Female"].astype("object")

X_learn.describe()

,Age,TP,ALB,AR,DBratio,logTB,logDB,logAlkphos,logSgpt,logSgot
count,620.000000,620.000000,620.000000,620.000000,620.000000,620.000000,620.000000,620.000000,620.000000,620.000000
mean,-0.084529,0.012748,0.081671,0.094800,0.082600,-0.142243,-0.138091,-0.138971,-0.131653,-0.147758
std,0.990065,0.984256,0.999751,0.972077,0.977447,0.901340,0.914212,0.913015,0.931855,0.935140
min,-2.506141,-3.577995,-2.841453,-2.172079,-1.447304,-1.368263,-1.236238,-2.484760,-1.798188,-1.731449
25%,-0.811937,-0.611033,-0.653920,-0.461597,-0.796602,-0.765409,-0.696750,-0.727952,-0.804747,-0.848766
50%,-0.004425,0.072263,0.118150,0.222596,0.029104,-0.536889,-0.467682,-0.384999,-0.289170,-0.381018
75%,0.677184,0.676594,0.890220,0.613294,0.479433,0.223516,0.382224,0.303460,0.352216,0.350354
max,2.743658,2.954046,2.305683,3.301464,3.415414,3.143281,2.818387,3.432619,3.724291,3.099199

In [10]:
def compute_metrics(y_pred, y_real):
    f1macro = f1_score(y_pred, y_real, average = "macro")
    f1_class0 = f1_score(y_pred, y_real, pos_label = 0)
    f1_class1 = f1_score(y_pred, y_real, pos_label = 1)
    accuracy = accuracy(y_pred, y_real)
    return [F1macro, mse, median_abs_e, mean_abs_e]

results = pd.DataFrame(columns = ['Kernel', 'C', 'epsilon', 'F1macro', 'F1 (class 0)', 'F2 (class 1)', 'Accuracy'])

## KNN (Baseline)

We are using KNN as a baseline for our SVM models.

## Linear SVM

We have to remove the Female variable because it is categorical.

In [ ]:
X_train, X_val, y_train, y_val = train_test_split(train_size = 0.80, random_state = 42)
X_train = X_train.drop()